### ISSUE TITLE
Option for simplified control?

### ISSUE THREAD

**Issue by JesseCake** [Solo-FL/SOLO-motor-controllers-ARDUINO-library#10]
Have been loving the look of your controllers to integrate into some robotics we're using, but honestly most of the functionality isn't necessary for what I'm after.

Do you have a "simplified serial" method of control much like Sabertooth controllers or Roboclaw controllers that allows sending of simple bytes to control output? 

An example of this is Sabertooth/Roboclaw commands for motors:
Send motor 1 forwards half speed: 96
Stop motor 1: 64
Reverse motor 1 half speed: 32
Send motor 2 forwards full speed: 255

This makes integration for simple tasks fast, easy, and low overhead. 

I realise this is for a control library, but logging this here in the hopes that simpler Arduino based comms can be achieved with your product to help adoption.

**Comment by Solo-FL** [comment]
Hi @JesseCake, we release a simple example that shows how to deal with your request here: 
https://github.com/Solo-FL/SOLO-motor-controllers-ARDUINO-library/blob/main/examples/uart/Sabertooth_Roboclow_Simple.ino

Is totally possible to make what you request, in the example the method you like "myCommands()" is just a switch between other SOLO methods with different names and values.  At the end of the example, you will see "cleanLoop()" an alternative of the "loop()" where instead of using the "myCommands()" are used the original SOLO methods.

We will remain at your disposal for support and clarification.
